services:
  - type: web
    name: f1-tracking-api
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /cache/fastf1
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: REDIS_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: cache
      mountPath: /cache
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80 